name: build-and-push-container-image

on:
    push:
        branches: ['docker-build-push']

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
    build-push-container-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4
            - name: build and push docker image
              run: |
                podman login -u $GITHUB_REPOSITORY_OWNER --password ${{ secrets.GITHUB_TOKEN }} ${{ env.GITHUB_REGISTRY }}
                podman build -t ghcr.io/$GITHUB_REPOSITORY_OWNER/podman-django:${{ github.sha }} -f ./django/webapp/Dockerfile ./django/webapp
                podman push ${{ env.GITHUB_REGISTRY }}/$GITHUB_REPOSITORY_OWNER/podman-django:${{ github.sha }}

