name: Build and push docker image

on:
  push:
    branches: ['main']
    
env:
    GITHUB_REGISTRY: ghcr.io
    DOCKER_IAMGE_NAME: ${{ github.repository }}

jobs:
    build-push-docker-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: login to ghcr.io
              uses: docker/login-action@v3
              with:
                registry: ${{ env.GITHUB_REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: extract the metadata (tags, labels)
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.GITHUB_REGISTRY }}/${{ env.DOCKER_IAMGE_NAME}}
            - name: build and push docker image
              uses: docker/build-push-action@v5
              with:
                context: ./django/webapp
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
